// 'use client'
import React from 'react'
// import React from 'react'
import { Geist, Geist_Mono } from "next/font/google";
import { Navbar } from "@components/navbar/navbar";
// import MyProvider from '@/app/components/MyProvider'; // wtest context
import { AlertProvider } from '@/app/contexts/AlertContext'
import { ModalProvider } from '@/app/contexts/ModalContext';
import AuthProvider from "@/app/contexts/SessionProvider";
// import { GoogleAnalytics } from "react-ga4"; // wtest ga wrong importga
// import { AnalyticsProvider } from '@/app/components/analyticsProvider/analyticsProvider'
import { GlobalProvider } from "@/app/contexts/GlobalContext";
import { ReduxProviders } from './providers'
import { store } from '@/../store'

import "./globals.css";
import '@styles/base/base.scss';

const GA4_MEASUREMENT_ID = process.env.GA4_MEASUREMENT_ID;// wtest GA4_MEASUREMENT_ID // wtest ga

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* wtest backup can't for use client *
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
/* /wtest backup can't for use client */

export default async function RootLayout({ children }) {
  
  const urlDomain = process.env.URL_DOMAIN + '/api/learning'
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProviders>
        {/* store={store} */}
          {/* <GoogleAnalytics /> */}
          {/* <AnalyticsProvider */}
            {/* gaMeasureId={GA4_MEASUREMENT_ID}> */}
            <GlobalProvider
              urlDomain={urlDomain}
              >
              <AuthProvider>
                
                <ModalProvider>
                  <AlertProvider>
                    <Navbar></Navbar>
                    {children}
                  </AlertProvider>
                </ModalProvider>
              </AuthProvider>
            </GlobalProvider>
          {/* </AnalyticsProvider> */}
          </ReduxProviders>
      </body>
    </html>
  );
}
