import React, { useContext } from 'react'
import { Geist, Geist_Mono } from "next/font/google";
import { Navbar } from "@components/navbar/navbar";
// import MyProvider from '@/app/components/MyProvider'; // wtest context
import { AlertProvider } from '@/app/contexts/AlertContext'
import { ModalProvider } from '@/app/contexts/ModalContext';
import AuthProvider from "@/app/components/SessionProvider";

import "./globals.css";
import '@styles/base/base.scss';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <Navbar></Navbar>
        
        <AlertProvider>
          <ModalProvider>
            {children}
          </ModalProvider>
        </AlertProvider>
      </body>
    </html>
  );
}


